import { ai } from "@/lib/ai";

interface ReportData {
  clientName: string;
  period: string;
  metrics: { revenue: number; leads: number; conversions: number; contentPieces: number; engagement: number };
  highlights: string[];
  agentActivity: Array<{ agent: string; tasks: number; results: string }>;
}

async function generateInsights(data: ReportData): Promise<string> {
  return ai(
    `Analyze this marketing performance and provide 3-5 key insights with actionable recommendations:
Revenue: $${data.metrics.revenue}
Leads: ${data.metrics.leads}
Conversions: ${data.metrics.conversions}
Content published: ${data.metrics.contentPieces}
Engagement: ${data.metrics.engagement}%
Period: ${data.period}

Be specific and strategic.`,
    { taskType: "analysis", system: "You are a marketing analytics expert. Provide concise, actionable insights." }
  );
}

/** Generate a branded HTML performance report */
export async function generateReport(data: ReportData): Promise<string> {
  const insights = await generateInsights(data);

  const metricCards = [
    { label: "Revenue", value: `$${data.metrics.revenue.toLocaleString()}`, color: "#00ff88" },
    { label: "Leads", value: data.metrics.leads.toString(), color: "#00d4ff" },
    { label: "Conversions", value: data.metrics.conversions.toString(), color: "#6c63ff" },
    { label: "Content", value: data.metrics.contentPieces.toString(), color: "#ff3366" },
  ].map(m => `
    <div style="background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:20px">
      <div style="color:${m.color};font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px">${m.label}</div>
      <div style="font-size:26px;font-weight:800;margin-top:8px">${m.value}</div>
    </div>
  `).join("");

  const highlightItems = data.highlights.map(h =>
    `<div style="color:#ccc;font-size:14px;line-height:1.8;padding-left:12px;border-left:2px solid rgba(108,99,255,0.3);margin-bottom:12px">${h}</div>`
  ).join("");

  const agentRows = data.agentActivity.map(a => `
    <div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid rgba(255,255,255,0.04)">
      <div>
        <div style="font-weight:600;font-size:14px">${a.agent}</div>
        <div style="color:#8888aa;font-size:12px">${a.results}</div>
      </div>
      <div style="background:rgba(0,255,136,0.1);color:#00ff88;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600">${a.tasks} tasks</div>
    </div>
  `).join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0a0a0f;color:#f0f0f5;font-family:Inter,-apple-system,sans-serif">
  <div style="max-width:640px;margin:0 auto;padding:40px 24px">
    <div style="text-align:center;margin-bottom:40px">
      <div style="font-size:13px;color:#6c63ff;font-weight:700;letter-spacing:2px;margin-bottom:8px">UMBRA</div>
      <h1 style="font-size:28px;margin:0;font-weight:800">Performance Report</h1>
      <p style="color:#8888aa;margin-top:8px">${data.clientName} • ${data.period}</p>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:32px">${metricCards}</div>
    <div style="background:rgba(108,99,255,0.05);border:1px solid rgba(108,99,255,0.15);border-radius:12px;padding:24px;margin-bottom:24px">
      <h2 style="font-size:16px;margin:0 0 16px;color:#6c63ff">🏆 Highlights</h2>
      ${highlightItems}
    </div>
    <div style="background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:24px;margin-bottom:24px">
      <h2 style="font-size:16px;margin:0 0 16px">🤖 Agent Activity</h2>
      ${agentRows}
    </div>
    <div style="background:rgba(0,212,255,0.05);border:1px solid rgba(0,212,255,0.15);border-radius:12px;padding:24px;margin-bottom:32px">
      <h2 style="font-size:16px;margin:0 0 16px;color:#00d4ff">🧠 AI Insights</h2>
      <div style="color:#ccc;font-size:14px;line-height:1.8;white-space:pre-wrap">${insights}</div>
    </div>
    <div style="text-align:center;color:#555;font-size:11px;padding-top:24px;border-top:1px solid rgba(255,255,255,0.04)">Generated by UMBRA — Shadow Intelligence</div>
  </div>
</body></html>`;
}
