"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Sparkles, FileText, Image, Search, Mail, Target, BarChart3, Globe, PenTool } from "lucide-react";
import { UmbraLogo } from "@/components/ui/UmbraLogo";

const SHOWCASE_ITEMS = [
  {
    category: "Content Generation",
    icon: FileText,
    title: "Blog posts written in your brand voice",
    description: "UMBRA analyzes your existing content and generates SEO-optimized blog posts that match your tone, style, and target audience. Each post is tailored to your industry.",
    examples: ["5 Hidden Gems in Constantia Wine Country", "Atlantic Seaboard: Investment Opportunity 2026", "Why Cape Town Luxury Real Estate Outperforms"],
    color: "#00B7FF",
  },
  {
    category: "Ad Creative",
    icon: Image,
    title: "Scroll-stopping ad copy and visuals",
    description: "Generate Facebook, Instagram, and Google ad variations with compelling copy, targeting suggestions, and A/B test alternatives — all aligned to your campaign goals.",
    examples: ["Facebook Carousel — Luxury Estate Tour", "Google Search — 'Best investment property Cape Town'", "Instagram Story — Open Day Invitation"],
    color: "#a855f7",
  },
  {
    category: "SEO",
    icon: Search,
    title: "Location pages that rank on Google",
    description: "Programmatic SEO pages targeting high-intent local keywords. Each page is unique, well-structured, and optimized for featured snippets and local pack results.",
    examples: ["12 Location Pages — Western Cape suburbs", "Meta descriptions optimized for CTR", "Schema markup auto-generated"],
    color: "#10b981",
  },
  {
    category: "Email Sequences",
    icon: Mail,
    title: "Drip campaigns that convert",
    description: "Multi-step email sequences for onboarding, nurture, re-engagement, and upselling. Each email is personalized and timed based on recipient behavior.",
    examples: ["5-Part Investment Opportunity Drip", "Post-viewing follow-up sequence", "Referral reward campaign"],
    color: "#f59e0b",
  },
  {
    category: "Competitor Intelligence",
    icon: Target,
    title: "Know what your competitors are doing",
    description: "Track competitor landing pages, ad spend, keyword rankings, and content strategy. Get weekly reports on what's working in your market.",
    examples: ["Competitor ad library monitoring", "Keyword gap analysis", "Content strategy comparison"],
    color: "#ef4444",
  },
  {
    category: "Analytics & Reporting",
    icon: BarChart3,
    title: "Client reports generated automatically",
    description: "Weekly and monthly reports showing campaign performance, lead generation metrics, content engagement, and ROI — formatted and ready to share.",
    examples: ["Monthly performance dashboard", "Lead source attribution", "Content engagement heatmap"],
    color: "#6366f1",
  },
];

export default function ShowcasePage() {
  return (
    <div className="min-h-screen bg-[#050505] text-white">
      {/* Nav */}
      <nav className="fixed top-0 inset-x-0 z-50 bg-[#050505]/80 backdrop-blur-md border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <UmbraLogo size="md" />
            <span className="text-xl font-bold tracking-[0.2em] uppercase text-white font-serif">UMBRA</span>
          </Link>
          <Link href="/" className="text-sm text-neutral-400 hover:text-white transition-colors">← Back</Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-40 pb-20 px-6 text-center relative">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(0,183,255,0.06),transparent_60%)]" />
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative z-10">
          <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 rounded-full px-4 py-2 mb-8">
            <Sparkles className="w-4 h-4 text-[#00B7FF]" />
            <span className="text-xs uppercase tracking-widest text-neutral-400">Proof of Work</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-white serif-text mb-6">See What UMBRA<br/>Actually Produces</h1>
          <p className="text-lg text-neutral-400 max-w-2xl mx-auto">Real examples of content, ads, SEO pages, and campaigns generated by our 29 AI marketing tools.</p>
        </motion.div>
      </section>

      {/* Showcase Grid */}
      <section className="py-16 px-6">
        <div className="max-w-5xl mx-auto space-y-16">
          {SHOWCASE_ITEMS.map((item, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="grid md:grid-cols-2 gap-8 items-start"
            >
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: `${item.color}15`, border: `1px solid ${item.color}30` }}>
                    <item.icon className="w-5 h-5" style={{ color: item.color }} />
                  </div>
                  <span className="text-xs uppercase tracking-widest text-neutral-500">{item.category}</span>
                </div>
                <h3 className="text-xl md:text-2xl font-bold text-white mb-3">{item.title}</h3>
                <p className="text-sm text-neutral-400 leading-relaxed">{item.description}</p>
              </div>
              <div className="bg-[#0a0a0a] border border-white/5 rounded-2xl p-6">
                <div className="flex items-center gap-2 mb-4">
                  <div className="w-2 h-2 rounded-full" style={{ backgroundColor: item.color }} />
                  <span className="text-xs text-neutral-500 font-mono uppercase">Example outputs</span>
                </div>
                <ul className="space-y-3">
                  {item.examples.map((example, j) => (
                    <li key={j} className="flex items-start gap-3">
                      <div className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ backgroundColor: item.color }} />
                      <span className="text-sm text-neutral-300">{example}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 text-center px-6 border-t border-glass-border">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
          <h2 className="text-3xl md:text-4xl font-bold text-white serif-text mb-4">Ready to see it work for you?</h2>
          <p className="text-neutral-400 mb-8">Start your free trial — no credit card required.</p>
          <Link href="/sovereign" className="inline-flex items-center gap-2 px-10 py-4 bg-gradient-to-r from-[#00B7FF] to-[#a855f7] text-white font-bold rounded-full text-lg cta-glow hover:-translate-y-0.5 transition-all">
            Get Started Free <ArrowRight className="w-5 h-5" />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-glass-border py-8 px-6 text-center">
        <p className="text-xs text-neutral-600">© 2026 UMBRA. All rights reserved.</p>
      </footer>
    </div>
  );
}
